# Generated by Django 5.2.17 on 2026-09-24 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('RESTOCK', 'Restock (Warehouse receipt)'), ('SALE', 'Sale (Order deduction)'), ('ADJUSTMENT', 'Adjustment (Compensating entry)'), ('RETURN', 'Return (Restocked return)')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='orders.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'db_table': 'stock_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='idx_stk_prod_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('transaction_type__in', ['RESTOCK', 'SALE', 'ADJUSTMENT', 'RETURN'])), name='chk_stk_type')],
            },
        ),
    ]
