# Generated by Django 5.2.17 on 2026-09-24 06:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_company_name', models.CharField(default='Vee Power Electricals', max_length=200)),
                ('brand_name', models.CharField(default='Vee Power Electricals', max_length=150)),
                ('gstin', models.CharField(default='33AABFV1234A1ZX', max_length=15)),
                ('pan', models.CharField(default='AABFV1234A', max_length=10)),
                ('registered_address', models.TextField(default='No 28/1, 2nd floor, MTP Road, Muthu nagar, NSN palayam, Coimbatore - 641031')),
                ('warehouse_address', models.TextField(default='No 28/1, 2nd floor, MTP Road, Muthu nagar, NSN palayam, Coimbatore - 641031')),
                ('support_email', models.EmailField(default='support@veepower.in', max_length=255)),
                ('support_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('bank_name', models.CharField(default='State Bank of India', max_length=150)),
                ('bank_account_number', models.CharField(default='38492019482', max_length=50)),
                ('bank_ifsc', models.CharField(default='SBIN0001234', max_length=20)),
                ('bank_branch', models.CharField(default='Coimbatore Main Branch', max_length=100)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('rounding_mode', models.CharField(choices=[('ROUND_HALF_UP', 'Round Half Up'), ('NO_ROUNDING', 'No Rounding')], default='ROUND_HALF_UP', max_length=20)),
                ('auto_cancel_unpaid_minutes', models.PositiveIntegerField(default=30)),
                ('cancellation_allowed_until', models.CharField(default='CONFIRMED', max_length=30)),
                ('return_window_days', models.PositiveIntegerField(default=7)),
                ('require_shipping_awb', models.BooleanField(default=True)),
                ('upi_enabled', models.BooleanField(default=True)),
                ('cards_enabled', models.BooleanField(default=True)),
                ('netbanking_enabled', models.BooleanField(default=True)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('cod_max_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('guest_checkout_enabled', models.BooleanField(default=False)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_notice', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company & Store Configuration',
                'verbose_name_plural': 'Company & Store Configurations',
                'db_table': 'company_store_configurations',
                'constraints': [models.CheckConstraint(condition=models.Q(('rounding_mode__in', ['ROUND_HALF_UP', 'NO_ROUNDING'])), name='chk_store_rounding'), models.CheckConstraint(condition=models.Q(('cod_max_limit__gte', 0)), name='chk_cod_limit')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_name', models.CharField(default='Vee Power Coimbatore Hub', max_length=150)),
                ('origin_address', models.CharField(default='No 28/1, 2nd floor, MTP Road, NSN palayam', max_length=255)),
                ('origin_city', models.CharField(default='Coimbatore', max_length=100)),
                ('origin_state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('origin_pincode', models.CharField(default='641031', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=Decimal('11.084800'), max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=Decimal('76.941600'), max_digits=9, null=True)),
                ('base_delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('distance_slab_km', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('charge_per_slab', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('999.00'), max_digits=12)),
                ('fallback_regional_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('free_delivery_enabled', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Configuration',
                'verbose_name_plural': 'Delivery Configurations',
                'db_table': 'delivery_configurations',
            },
        ),
        migrations.CreateModel(
            name='DistanceSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='commercial_config.deliveryconfiguration')),
            ],
            options={
                'verbose_name': 'Distance Slab',
                'verbose_name_plural': 'Distance Slabs',
                'db_table': 'distance_slabs',
                'ordering': ['sort_order', 'min_distance_km'],
            },
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Rupee Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usage_limit_total', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1)),
                ('allow_stacking', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Discount',
                'verbose_name_plural': 'Order Discounts',
                'db_table': 'order_discounts',
            },
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=100, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_days_min', models.PositiveIntegerField(default=2)),
                ('estimated_days_max', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shipping Rule',
                'verbose_name_plural': 'Shipping Rules',
                'db_table': 'shipping_rules',
                'constraints': [models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='chk_ship_cost')],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_name', models.CharField(default='Indian Standard GST', max_length=100)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('tax_calculation_mode', models.CharField(choices=[('TAX_EXCLUSIVE', 'Tax Exclusive (Added at checkout)'), ('TAX_INCLUSIVE', 'Tax Inclusive (Extracted backwards)')], default='TAX_EXCLUSIVE', max_length=20)),
                ('business_state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configurations',
                'db_table': 'tax_configurations',
            },
        ),
        migrations.AddIndex(
            model_name='deliveryconfiguration',
            index=models.Index(fields=['is_active', 'effective_from', 'effective_until'], name='idx_del_lookup'),
        ),
        migrations.AddConstraint(
            model_name='deliveryconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('base_delivery_charge__gte', 0), ('distance_slab_km__gt', 0)), name='chk_del_params'),
        ),
        migrations.AddConstraint(
            model_name='deliveryconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('charge_per_slab__gte', 0), ('free_delivery_threshold__gte', 0), ('fallback_regional_rate__gte', 0)), name='chk_del_aux_params'),
        ),
        migrations.AddIndex(
            model_name='distanceslab',
            index=models.Index(fields=['delivery_config', 'min_distance_km', 'max_distance_km'], name='idx_slabs_config_range'),
        ),
        migrations.AddConstraint(
            model_name='distanceslab',
            constraint=models.CheckConstraint(condition=models.Q(('max_distance_km__gt', models.F('min_distance_km')), ('min_distance_km__gte', 0)), name='chk_slab_range'),
        ),
        migrations.AddConstraint(
            model_name='distanceslab',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='chk_slab_rate'),
        ),
        migrations.AddConstraint(
            model_name='orderdiscount',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type__in', ['percentage', 'fixed'])), name='chk_coupon_type'),
        ),
        migrations.AddConstraint(
            model_name='orderdiscount',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='chk_coupon_value_pos'),
        ),
        migrations.AddConstraint(
            model_name='orderdiscount',
            constraint=models.CheckConstraint(condition=models.Q(('min_order_value__gte', 0)), name='chk_coupon_min_order'),
        ),
        migrations.AddIndex(
            model_name='taxconfiguration',
            index=models.Index(fields=['is_active', 'effective_from', 'effective_until'], name='idx_tax_lookup'),
        ),
        migrations.AddConstraint(
            model_name='taxconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('tax_calculation_mode__in', ['TAX_EXCLUSIVE', 'TAX_INCLUSIVE'])), name='chk_tax_mode'),
        ),
        migrations.AddConstraint(
            model_name='taxconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('default_tax_rate__gte', 0), ('cgst_rate__gte', 0), ('sgst_rate__gte', 0), ('igst_rate__gte', 0)), name='chk_tax_rates'),
        ),
    ]
