# Generated by Django 5.2.17 on 2026-10-06 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Master switch for configurable outbound customer email.')),
                ('order_notifications', models.BooleanField(default=True, help_text='Order confirmation and fulfilment lifecycle notifications.')),
                ('payment_notifications', models.BooleanField(default=True, help_text='Payment confirmation and payment failure notifications.')),
                ('invoice_notifications', models.BooleanField(default=True, help_text='Statutory GST tax invoice issuance notifications.')),
                ('quotation_notifications', models.BooleanField(default=True, help_text='Commercial quotation create/approve/reject notifications.')),
                ('customer_notifications', models.BooleanField(default=True, help_text='Account registration welcome and inquiry acknowledgement notifications.')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Administrator who last changed this policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'notification_settings',
            },
        ),
    ]
