# Generated by Django 5.2.17 on 2026-10-03 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google')], default='google', max_length=20)),
                ('event_type', models.CharField(choices=[('GOOGLE_LOGIN', 'Google Identity Login'), ('GOOGLE_REGISTER', 'Google Identity Registration'), ('GOOGLE_LINK', 'Google Identity Linked'), ('LINK_REJECTED', 'Account Linking Rejected'), ('DUPLICATE_IDENTITY', 'Duplicate Identity Attempt'), ('LINK_CONFLICT', 'Account Link Conflict')], max_length=30)),
                ('provider_subject', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity Audit Log',
                'verbose_name_plural': 'Identity Audit Logs',
                'db_table': 'identity_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='idx_identity_event_created'), models.Index(fields=['provider_subject'], name='idx_identity_subject')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['GOOGLE_LOGIN', 'GOOGLE_REGISTER', 'GOOGLE_LINK', 'LINK_REJECTED', 'DUPLICATE_IDENTITY', 'LINK_CONFLICT'])), name='chk_identity_event_type')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google')], default='google', max_length=20)),
                ('provider_subject', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'social_accounts',
                'indexes': [models.Index(fields=['user'], name='idx_social_user'), models.Index(fields=['email'], name='idx_social_email')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_subject'), name='uniq_social_provider_subject')],
            },
        ),
    ]
