# Generated by Django 5.2.17 on 2026-10-10 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_identityauditlog_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255)),
                ('token', models.CharField(db_index=True, max_length=100)),
                ('otp', models.CharField(blank=True, default='', max_length=10)),
                ('token_type', models.CharField(choices=[('EMAIL_VERIFY', 'Email Verification'), ('EMAIL_CHANGE', 'Email Change')], default='EMAIL_VERIFY', max_length=30)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'email_verification_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'otp', 'is_used'], name='idx_evt_email_otp_used'), models.Index(fields=['token', 'is_used'], name='idx_evt_token_used'), models.Index(fields=['user', 'token_type'], name='idx_evt_user_type')],
            },
        ),
    ]
