# Generated by Django 5.2.17 on 2026-09-24 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New Ticket'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'db_table': 'contact_inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_inq_status_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['New', 'In Progress', 'Resolved', 'Closed'])), name='chk_inquiry_status')],
            },
        ),
        migrations.CreateModel(
            name='AdminConfigAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('record_id', models.BigIntegerField()),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DEACTIVATE', 'Deactivate'), ('DELETE', 'Delete')], max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(default=dict)),
                ('change_reason', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Config Audit Log',
                'verbose_name_plural': 'Admin Config Audit Logs',
                'db_table': 'admin_config_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'record_id', 'created_at'], name='idx_audit_domain_rec')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action_type__in', ['CREATE', 'UPDATE', 'DEACTIVATE', 'DELETE'])), name='chk_audit_action')],
            },
        ),
    ]
