# Generated by Django 5.2.17 on 2026-10-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_communicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='html_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='locked_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='provider',
            field=models.CharField(blank=True, default='brevo', max_length=50),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='provider_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='text_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('SUPPRESSED', 'Suppressed')], default='SENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['status', 'next_retry_at'], name='idx_comm_stat_retry'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['provider_message_id'], name='idx_comm_prov_msgid'),
        ),
    ]
