# Generated by Django 5.2.17 on 2026-10-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('order__isnull', False), ('invoice__isnull', False), _connector='OR'), name='chk_pay_reference'),
        ),
    ]
