# Generated by Django 5.2.17 on 2026-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_payment_reference_check'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway_order_id'], name='idx_pay_gateway_order_id'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status'], name='idx_pay_order_status'),
        ),
    ]
